---
title: "Base R"
format: html
editor: visual
---

## Task 1: Basic Vector Practice

```{r}
#Creating pre-treatment values
pre<-c(120,151,125,126,115,132,132,129,134,139,127,122,127,135,133,128,147,138,140,132)

#Creating post-treatment values
post<-c(127,145,135,122,115,122,123,126,126,129,132,146,120,114,121,120,128,120,133,115)

#Assigning attributes to vectors
paste("Subject",1:20,sep="_")

names(pre)<-paste("Subject",1:20,sep="_")

names(post)<-paste("Subject",1:20,sep="_")

#Calculating Change in BP vector
chg<-c(pre-post)

#Average decrease in BP
mean(chg)

#Determining who has a decrease in BP
which(chg>0)

#Subsetting Vector
chg[chg>0]

#Calculating Average decrease for those who had positive change

mean(chg[chg>0])
```

## Task 2: Basic Data Frame Practice

```{r}
#Creating Data Frame
all<-data.frame(pre_bp=pre,post_bp=post,diff_bp=chg)


#Subsetting on rows where change in BP is negative
all$diff_bp[all$diff_bp<0]

all<-data.frame(pre_bp=pre,post_bp=post,diff_bp=chg,tf=ifelse(all$post_bp<120,'TRUE','FALSE'))

all

knitr::kable(all)
```

##Task3 List Practice

```{r}
pretreat<-c(138,135,147,117,152,134,114,121,131,130)

posttreat<-c(105,136,123,130,134,143,135,139,120,124)

names(pretreat)<-paste("Subject",1:10,sep="_")

names(posttreat)<-paste("Subject",1:10,sep="_")

all2<-data.frame(pre_treat=pretreat,post_treat=posttreat,tf=ifelse(all2$post_treat<120,"True","False"))


```

